insert into arenas (id, arena_name) values (1, 'Wisoky LLC');
insert into arenas (id, arena_name) values (2, 'Kris-Erdman');
insert into arenas (id, arena_name) values (3, 'Reinger, Rath and Heaney');
insert into arenas (id, arena_name) values (4, 'Strosin-Hilpert');
insert into arenas (id, arena_name) values (5, 'Jakubowski, Gibson and Becker');
insert into arenas (id, arena_name) values (6, 'Bahringer, Schiller and Willms');
insert into arenas (id, arena_name) values (7, 'Metz LLC');
insert into arenas (id, arena_name) values (8, 'Beahan and Sons');
insert into arenas (id, arena_name) values (9, 'McClure, Olson and Gutkowski');
insert into arenas (id, arena_name) values (10, 'Kunze, Lockman and McCullough');
insert into arenas (id, arena_name) values (11, 'Gusikowski, Hilpert and Hettinger');
insert into arenas (id, arena_name) values (12, 'Konopelski and Sons');
insert into arenas (id, arena_name) values (13, 'Casper Inc');
insert into arenas (id, arena_name) values (14, 'Kohler-Cummings');
insert into arenas (id, arena_name) values (15, 'Macejkovic, Grant and Hand');
insert into arenas (id, arena_name) values (16, 'Hudson-Zulauf');
insert into arenas (id, arena_name) values (17, 'Little Group');
insert into arenas (id, arena_name) values (18, 'Hintz and Sons');
insert into arenas (id, arena_name) values (19, 'Wilkinson and Sons');
insert into arenas (id, arena_name) values (20, 'Christiansen-Pagac');
insert into arenas (id, arena_name) values (21, 'Marquardt-Reynolds');
insert into arenas (id, arena_name) values (22, 'Roob, Kerluke and Parisian');
insert into arenas (id, arena_name) values (23, 'Balistreri Group');
insert into arenas (id, arena_name) values (24, 'Emmerich-Ankunding');
insert into arenas (id, arena_name) values (25, 'Zboncak LLC');
insert into arenas (id, arena_name) values (26, 'Barrows-Erdman');
insert into arenas (id, arena_name) values (27, 'Collins-Pacocha');
insert into arenas (id, arena_name) values (28, 'Spencer, Lemke and Bode');
insert into arenas (id, arena_name) values (29, 'Murray, Toy and Donnelly');
insert into arenas (id, arena_name) values (30, 'Fay, Thiel and Will');
insert into arenas (id, arena_name) values (31, 'Romaguera and Sons');
insert into arenas (id, arena_name) values (32, 'Yundt, Breitenberg and Mosciski');
insert into arenas (id, arena_name) values (33, 'Turcotte Group');
insert into arenas (id, arena_name) values (34, 'Lang, Douglas and Muller');
insert into arenas (id, arena_name) values (35, 'Reichert, Crist and McKenzie');
insert into arenas (id, arena_name) values (36, 'Marquardt Group');
insert into arenas (id, arena_name) values (37, 'Armstrong Group');
insert into arenas (id, arena_name) values (38, 'Willms, Parker and Tromp');
insert into arenas (id, arena_name) values (39, 'Brakus-Effertz');
insert into arenas (id, arena_name) values (40, 'Roob, Koss and Swift');
insert into arenas (id, arena_name) values (41, 'Bode, Baumbach and Hilll');
insert into arenas (id, arena_name) values (42, 'Metz LLC');
insert into arenas (id, arena_name) values (43, 'Ziemann Group');
insert into arenas (id, arena_name) values (44, 'Schiller-Cormier');
insert into arenas (id, arena_name) values (45, 'Upton LLC');
insert into arenas (id, arena_name) values (46, 'Romaguera LLC');
insert into arenas (id, arena_name) values (47, 'Hand-Jaskolski');
insert into arenas (id, arena_name) values (48, 'Baumbach and Sons');
insert into arenas (id, arena_name) values (49, 'Koch Inc');
insert into arenas (id, arena_name) values (50, 'Zieme and Sons');
insert into arenas (id, arena_name) values (51, 'Turner-Leannon');
insert into arenas (id, arena_name) values (52, 'Goodwin, Yundt and Mohr');
insert into arenas (id, arena_name) values (53, 'Langworth-Bosco');
insert into arenas (id, arena_name) values (54, 'Harris and Sons');
insert into arenas (id, arena_name) values (55, 'O''Connell-Wisoky');
insert into arenas (id, arena_name) values (56, 'Reichel, Sipes and Nienow');
insert into arenas (id, arena_name) values (57, 'Leuschke-Nitzsche');
insert into arenas (id, arena_name) values (58, 'Fay-Rohan');
insert into arenas (id, arena_name) values (59, 'Swift, Jerde and Kuphal');
insert into arenas (id, arena_name) values (60, 'Balistreri, Cremin and Kub');
insert into arenas (id, arena_name) values (61, 'Veum and Sons');
insert into arenas (id, arena_name) values (62, 'Reinger-Rowe');
insert into arenas (id, arena_name) values (63, 'Hoppe, Bernhard and Grant');
insert into arenas (id, arena_name) values (64, 'Stark, Aufderhar and Wyman');
insert into arenas (id, arena_name) values (65, 'Quitzon, Zboncak and Runolfsson');
insert into arenas (id, arena_name) values (66, 'Bogisich, Weber and Kirlin');
insert into arenas (id, arena_name) values (67, 'Kertzmann, Murazik and Wunsch');
insert into arenas (id, arena_name) values (68, 'White LLC');
insert into arenas (id, arena_name) values (69, 'DuBuque-Thiel');
insert into arenas (id, arena_name) values (70, 'Breitenberg and Sons');
insert into arenas (id, arena_name) values (71, 'McDermott and Sons');
insert into arenas (id, arena_name) values (72, 'Schiller, Daugherty and Cartwright');
insert into arenas (id, arena_name) values (73, 'Rohan, Beer and Crona');
insert into arenas (id, arena_name) values (74, 'Treutel-Hermiston');
insert into arenas (id, arena_name) values (75, 'Aufderhar and Sons');
insert into arenas (id, arena_name) values (76, 'MacGyver, Franecki and Champlin');
insert into arenas (id, arena_name) values (77, 'Pfannerstill-Davis');
insert into arenas (id, arena_name) values (78, 'Lind and Sons');
insert into arenas (id, arena_name) values (79, 'Nikolaus Group');
insert into arenas (id, arena_name) values (80, 'Rath, Ziemann and Donnelly');
insert into arenas (id, arena_name) values (81, 'Lowe, Nienow and Bernhard');
insert into arenas (id, arena_name) values (82, 'Kreiger-Schuster');
insert into arenas (id, arena_name) values (83, 'Osinski, Hintz and Bednar');
insert into arenas (id, arena_name) values (84, 'Blick, Kuvalis and Weber');
insert into arenas (id, arena_name) values (85, 'Berge-Anderson');
insert into arenas (id, arena_name) values (86, 'Hackett, Toy and Schuster');
insert into arenas (id, arena_name) values (87, 'Kovacek, Runolfsson and Koelpin');
insert into arenas (id, arena_name) values (88, 'Jakubowski-Kuvalis');
insert into arenas (id, arena_name) values (89, 'Bogan, Gislason and Armstrong');
insert into arenas (id, arena_name) values (90, 'Corkery Inc');
insert into arenas (id, arena_name) values (91, 'Grant, Hayes and Braun');
insert into arenas (id, arena_name) values (92, 'Jenkins, Langosh and Christiansen');
insert into arenas (id, arena_name) values (93, 'Collier Inc');
insert into arenas (id, arena_name) values (94, 'Weimann, Schumm and Skiles');
insert into arenas (id, arena_name) values (95, 'Marvin, McLaughlin and Johns');
insert into arenas (id, arena_name) values (96, 'Dach and Sons');
insert into arenas (id, arena_name) values (97, 'Abernathy-Dach');
insert into arenas (id, arena_name) values (98, 'Leffler-McCullough');
insert into arenas (id, arena_name) values (99, 'Hodkiewicz, O''Connell and Daniel');
insert into arenas (id, arena_name) values (100, 'Brakus-Mraz');
